### ISSUE TITLE
Doesn't run with python3 Small patch

### ISSUE THREAD

**Issue by firstnevyn** [JonasSC/FTU-Mixer#1]
Hi Jonas,

I've patched this to at least attempt to run with python3 as I couldn't find the alsa bindings for python2 in debian anymore. had a couple of little syntax things to fix to make it run. I still havn't tested with the device as I've loaned it out at the moment to someone.

index badada1..97e9f6a 100755
--- a/source/ftumixer.py
+++ b/source/ftumixer.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 
 # Copyright 2013 Jonas Schulte-Coerne
 #
@@ -621,7 +621,7 @@ if __name__ == "__main__":
                        card_index = i
                i += 1
        if card_index is None:
-               print "No M-Audio Fast Track Ultra found. Exiting..."
+               print ("No M-Audio Fast Track Ultra found. Exiting...")
        else:
                # parse command line arguments
                parser = argparse.ArgumentParser(description="A little mixer for the M-Audio Fast Track Ultra audio interfaces.")

**Comment by JonasSC** [comment]
Hi Grant,
Thank you very much for your contribution!
I'm sorry, that it took me so long to reply. I was on vacation in the end of February, so I could not include your fix immediately and then I forgot about it until another pull request for FTU-Mixer came in yesterday.
I have included your fix for Python 3 compatibility and updated FTU-Mixer to work with wxPython 4.0, so it should run on current operating systems. I've tested it on my RaspberryPi with a current version of Raspbian.
Best regards,
  Jonas
